CREATE TABLE IF NOT EXISTS COUPONS (
     COUPON_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     CODE VARCHAR(255) NOT NULL,
     CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     MAX_USAGES INT NOT NULL,
     CURRENT_USAGES INT NOT NULL DEFAULT 0,
     COUNTRY VARCHAR(100) NOT NULL,
     CONSTRAINT UK_COUPONS_CODE UNIQUE (CODE)
);