CREATE TABLE IF NOT EXISTS USER_COUPON_USAGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COUPON_ID BIGINT NOT NULL,
    USER_NAME VARCHAR (255) NOT NULL,
    USAGE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usage_to_coupons FOREIGN KEY (COUPON_ID) REFERENCES COUPONS(COUPON_ID)
)